"""add sale id to inventory movements

Revision ID: f1fd9fd795d5
Revises: f1a24c2516b2
Create Date: 2026-09-11 12:02:15.308848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1fd9fd795d5'
down_revision: Union[str, Sequence[str], None] = 'f1a24c2516b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movements', sa.Column('sale_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inventory_movements_sale_id'), 'inventory_movements', ['sale_id'], unique=False)
    op.create_foreign_key(None, 'inventory_movements', 'sales', ['sale_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_movements_sale_id'), table_name='inventory_movements')
    op.drop_column('inventory_movements', 'sale_id')
    # ### end Alembic commands ###
